### ISSUE TITLE
match_taxa mistake: Solanum lycopersicum (tomato) in a bacterial genus Sphingomonas [bug in clobberName]

### ISSUE THREAD

**Issue by karolisr** [OpenTreeOfLife/reference-taxonomy#100]
To replicate:

```
curl -X POST http://devapi.opentreeoflife.org/v2/tnrs/match_names -H "content-type:application/json" -d '{"names":["Solanum lycopersicum"]}'
```

Two hits are returned. One is correct: _Solanum lycopersicum_ (species in tribe _Solaneae_). The other one is _Solanum lycopersicum_ (in genus _Sphingomonas_). _Sphingomonas_ is a bacterial genus [found on tomatoes](http://www.biomedcentral.com/1471-2180/13/114). Something seems to be amiss, the bacterial hit points to NCBI Taxonomy ID [4081](http://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi?mode=Info&id=4081), which is tomato.

**Comment by jar398** [comment]
Note to self: it's better than it was, since one will see for the bad entry that the second sense of "Solanum lycopersicum" is as a synonym for something called "Not Solanum lycopersicum", and it should be pretty clear, at least to a human, that that is not the one they want.

But this is still a bug (in Taxon.clobberName) - it shouldn't be offered at all. I'm leaving this issue open and reclassifying it as a bug.

**Comment by jar398** [comment]
I think the bug is fixed in the code, but won't be reflected in the taxonomy until OTT 2.10. In the meantime you see this, which ought to be a big hint:

```{
      "matched_node_id" : 4205079,
      "synonyms" : [ "Not Solanum lycopersicum", "Solanum lycopersicum" ],
      "flags" : [ ],
      "ot:ottTaxonName" : "Not Solanum lycopersicum", ...```
