### ISSUE TITLE
explanation of "rank" field

### ISSUE THREAD

**Issue by mtholder** [OpenTreeOfLife/reference-taxonomy#118]
Sorry if I'm just missing this in the docs. Could we add a page to the Wiki to summarize what (if anything) a user of OTT can assume is true of the rank field.

In OTT 2.8 Mammalia (id = 244265) is a descendant of Sarcopterygii (id=458402). But both are listed as having the rank "class"

I'm not sure if I should report that as an issue with the taxonomy or whether we just don't guarantee that the ranks are sensible on output.

**Comment by jar398** [comment]
I think we should just say the ranks aren't sensible.

Currently the rank given in OTT is the rank given in the highest priority
taxonomy in which the taxon occurs. If you want some other way to calculate
rank, we can talk about changing it, but otherwise I don't see what else to
do. I assumed that this was low priority on a taxonomy project, although I
realized recently that rank has at least one purpose: distinct taxa of the
same rank are necessarily disjoint.

(There are even a few taxa for which the ranks are out of order, but I
suspect they're all mistakes.

** Ranks out of order: (if:21291 Saccharomycetes) genus has child (if:90341
Saccharomycetidae) subclass
** Ranks out of order: (gbif:4865225 Chonetoidea) genus has child
(gbif:3252122 Eodevonariidae) family
** Ranks out of order: (gbif:4587706 Nuculoidea) genus has child
(gbif:4587862 Nucularcidae) family
** Ranks out of order: (gbif:2050173 Alydus calcaratus) species has child
(gbif:3265607 Camptopus) genus
** Ranks out of order: (gbif:1010609 Limulus) genus has child (gbif:4632823
Paleomeridae) family
)

**Comment by mtholder** [comment]
I'm fine with saying that they are not to be trusted. just wanted to make sure that you did not want me to file issues for cases in which the ranks don't make sense.
I'll add a statement to the wiki.

**Comment by mtholder** [comment]
I added at **Note:** to the rank column info at https://github.com/OpenTreeOfLife/reference-taxonomy/wiki/General-information
