### ISSUE TITLE
Artiodactyla placement is odd

### ISSUE THREAD

**Issue by mtholder** [OpenTreeOfLife/reference-taxonomy#120]

**Comment by mtholder** [comment]
oops accidentally submitted without the description:

We have Artiodactyla:

    3615249	|	244265	|	Artiodactylaa	|	order	|	gbif:731,irmng:11174	|		|	sibling_lower,tattered	|

and Cetartiodactyla:

    622916	|	392223	|	Cetartiodactyla	|	no rank	|	ncbi:91561	|		|		|	

these should be synonymized.
See https://github.com/OpenTreeOfLife/feedback/issues/58

**Comment by jar398** [comment]
If a simple synonymy is enough then the fix is trivial, just one line to
make-ott.py.

If I remember correctly when I looked at this earlier, all the remaining
descendants of artiodactyla after taxonomy integration are extinct. There
is code to mark as extinct taxa all of whose children are extinct (I know
because it was marking Homo sapiens as extinct at one point!), but it
failed in this case because we didn't have extinct annotations for all
those taxa. Ordinarily those annotations would come from IRMNG but IRMNG
treated them as extant.

**Comment by jar398** [comment]
Fixed in 2.9draft2
