### ISSUE TITLE
Should these Bacteria be marked environmental?

### ISSUE THREAD

**Issue by bredelings** [OpenTreeOfLife/reference-taxonomy#196]
Bacteria has about 50,000 children that are species, and this goes down to about 27,000 if you ignore environmental samples.  However, a lot of the remaining 27,000 species have names like:

5201905   'uncultured candidate division WS5 bacterium'   'species'   depth = 4   out-degree
5191779   'marine snow associated bacterium Adriatic77'   'species'   depth = 4   out-degree
5182885   'agricultural soil bacterium SC-I-55'   'species'   depth = 4   out-degree = 0
5187699   'uncultured Banisveld landfill bacterium BVB15'   'species'   depth = 4   out-degr
5201231   'uncultured feedlot manure bacterium B35'   'species'   depth = 4   out-degree = 0
5274633   'bacterium BM0160'   'species'   depth = 4   out-degree = 0
4758318   'bacterium endosymbiont of Hackeriella brachycephala'   'species'   depth = 4   ou
4755636   'swine fecal bacterium FPC23B'   'species'   depth = 4   out-degree = 0
5568496   'bacterium B5GN'   'species'   depth = 4   out-degree = 0
4765882   'bacterium ocme08sprnp685'   'species'   depth = 4   out-degree = 0
4752607   'Gram-negative bacterium TA59'   'species'   depth = 4   out-degree = 0

Most of these don't actually have the word "uncultured" in their names, but still seem environmental to me.

Should we (in theory) classify these as environmental?  How hard would that be?

This could become an issue after we start handling incertae sedis taxa, because all but 91 of these are listed as unclassified, but not environmental.  So, we currently exclude them from the synthetic tree, but would stop if we included unclassifed taxa.

**Comment by bredelings** [comment]
% otc-taxonomy-parser -C 844192 --clean=environmental  | grep species

Apologies, but this command is not yet fully documented.  It assumes you have an ~/.opentree file that contains:

[opentree]
ott=/path/to/ott

**Comment by jar398** [comment]
Despite their names these are perfectly good taxa - they come from SILVA
and Laura Katz explicitly requested that these be included in the tree.
Each has a set of genbank sequences and a chosen reference sequence, so
they're taxa in the sense that new things can be placed in them.

If anything the problem is the name, which comes from NCBI, not SILVA, and
often reflects the fact that NCBI hasn't put them in its classification.
But SILVA has, and we take SILVA to be higher priority taxonomically than
NCBI.

I'm thinking of putting something like "cluster AB1234" in the name of all
of these taxa. This was also requested. This will require a little bit of
retooling, and a decision as to what the exact syntax should be. The word
"unclassified" should also not occur in the name of any of these SILVA
clusters.

On Wed, Apr 6, 2016 at 4:13 PM, Benjamin Redelings <notifications@github.com

**Comment by jar398** [comment]
The answer is 'no'.
