### ISSUE TITLE
Automatic process to incorporate community curated taxonomy contributions

### ISSUE THREAD

**Issue by jar398** [OpenTreeOfLife/reference-taxonomy#202]
Having me in the way of taxonomy changes is a bad idea.

I'm working hard to get this automated now and realized there was no issue for it.

**Comment by jar398** [comment]
There are two parts to this problem:
  - 'Phase I': simple taxon additions (usually new species for unmapped OTUs) to be initiated from study curator
  - 'Phase II': a 'patch' system to replace the current nonfunctioning tsv-file-based one, for dealing with the feedback issues
Phase I is top priority right now. @mtholder has proposed designing for phase I only with no consideration for phase II.  However, the requirements for the two are very similar, so I think designing only for phase I at this point, and locking out phase II or forcing changes in formats or protocols for when it becomes higher priority, would be short-sighted.  So I plan to do phase I but leaving enough extension points that phase II can be done later without a lot of rewriting. We are not talking about major differences here; the features needed in phase II but not phase I are synonyms, extinctness settings, duplicate removal (unification), and reclassification (changing a node's parent). To repeat, I'm not talking about putting the phase II features in the API right away, but rather designing the API so that they can be compatibly added later.

If we decide we won't ever do phase II then we should stop accepting taxonomy feedback, since I can't see processing the backlog of feedback changes without it (it = a declarative syntax suitable for interpretation in multiple contexts). I've done hundreds of these manually and the current process is way too time consuming and unwieldy (poor tracking, poor testing).

**Comment by mtholder** [comment]
Since I have not weighed in on this thread, I assume you are talking about the doc at: https://docs.google.com/document/d/1W-mlvVCoQdrFnKZbBuLCCGp9x35cz7oGZcJaiAmTv2Y/edit

That doc has lots of complexity. A lot of the complexity in that doc (I think) has to do with the desire that the "amendment" be generic and not specific to OTT. Generality is, of course, a nice feature when you consider it in a vaccuum. Realistically, it is very unlikely that any other taxonomy project will adopt our format for amendments in the next year. 

In this issue it sounds like there really isn't much difference between a proposal for just phase 1 and one that works for phase 1 and phase 2. But when you look at the doc, you see *lots* of compelexity in the service of generality. This is mainly centered around:
  * a registry of OTT IDs, and
  * generic amendments (which then require "internal ids" and amendments as first class entities [with names, IDs and comments]).

The alternative that I suggested (in that doc) is just to describe the new OTT taxon that the curator wants. API-arguments designed specifically for "phase 1" would only need:
  * A name supplied from curator, but that is the same for every taxon in OTT - so nothing new there. And this is also required in the other proposal.
  * The OTT ID. This comes from a simple incrementing counter - barely anything new there. Hell -- there is even an operator for that in most languages.
  * an OTT ID of parent. This is not general, but it is very simple - nothing new to Open Tree here.
  * some optional fields for provenance. Nice to have, but we won't really lean on them much for automated processing.

So the 2 proposals differ by quite a bit in terms of technical debt for the future of the project.

There is also the issue of transparency.  To be frank, the whole taxonomy side of this project has been plagued with very little clear, high level documentation/justification and with a whole lot of "it is not done optimally now, I'd like to reimplement it and then explain after it is fixed" in response to queries about how things work.  No one really understands how smasher works, so throwing in a generic amendment tool just makes a complex system more complex.

We are now about 1 year away from the end of our funding period. In my opinion, the working assumption should be: the open tree of life project of 2017 will probably need to revisit the tool for building OTT if/when we get more funding. There could well be a funding gap (hopefully short). There is a high probability that the person maintaining the taxonomy-combining code will be some one who is not familiar with smasher now. So documenting how things work right now and keeping things simple is a high priority (in my opinion).

In light of that, just implementing "phase 1" in the clearest possible way for accomplishing phase 1 is not short-sighted it is pragmatic. Building in lots of complexity so that we can maximize generality seems foolish, given the opaque nature and complexity of the current system.
