### ISSUE TITLE
treatment of monotypic taxa

### ISSUE THREAD

**Issue by kcranston** [OpenTreeOfLife/reference-taxonomy#269]
If I am reading the manuscript correctly, we remove monotypic taxa from OTT when the parent-child have the same name strings (see section [import and normalization](https://github.com/OpenTreeOfLife/reference-taxonomy/blob/work-on-draft/doc/method/method-details.md#import-and-normalization)). This means that our treatment of monotypic taxa in the synthetic tree differs depending on whether the names match: if the parent and child have different names, then the synthetic tree contains the monotypic taxa, but if the parent and child have the same names, the synthetic tree does not contain the monotypic taxa. I understand why this makes assembling OTT easier, but wanted to think about whether this is what we want in the synthetic tree.

**Comment by jar398** [comment]
Ah. Yes, that is a good question. Maybe all monotypic taxa should be
collapsed in OTT, not just the homonyms. This could done as a post-pass.
(The homonyms have to be handled early since there is no way to tell them
apart in alignment, but the others should be preserved until the end since
a later taxonomy may change the parent from monotypic to non-monotypic.)
I'm happy to implement whatever the synthetic tree editors would like.​

**Comment by jar398** [comment]
Decision reached at recent hangout: include all monotypic taxa in OTT, including the homonyms. Implementing this will require a tricky change in alignment, so that the parent is preferred to the child.

**Comment by jar398** [comment]
Have removed the monotypic-same-name logic.  There is one special case, for subgenera. In this situation a subgenus X of genus X is renamed "X subgenus X". This logic is exercised only for WoRMS, where it happens 1609 times.

I removed the rule from the writeup but haven't yet added the subgenus rule... making a note of it.
