### ISSUE TITLE
Backbone quality

### ISSUE THREAD

**Issue by kcranston** [OpenTreeOfLife/reference-taxonomy#297]
This section in results consists of two bullet points with analyses that could be done, but no actual results. The two suggestions are phylogenetic accuracy and resolution. How difficult to get a measure of resolution for each of the inputs?

**Comment by jar398** [comment]
These are both doable and fairly straightforward (i.e. no known-unknowns) but will require new scripts, each a couple of hours. Not starting quite from scratch since parts can be cobbled from other scripts.

**Comment by jar398** [comment]
The section will be called 'Phylogenetically informed classification' to match the introduction.

Phylogenetic informedness is a matter of  degree. We would like to say OTT is better informed than alternatives. To quantify this well would be hard. Something like: make a subtree of OTT (or whatever taxonomy is to be measured) whose tips are in the synthetic tree (before OTT-only taxonomy is added), and see how many conflicts there are. That doesn't quite work because it doesn't give a way to compare OTT and NCBI, or NCBI and GBIF - so maybe a 3-way or n-way intersection?

I'm writing the section to weasel around this question. I can't think of anything quantitative to say; if we report on the number of conflicting nodes (3181 in synth 8.0), we give a number that the reader has no way to interpret, at least in this context - no way to tell if the number is smaller than expected or larger.
