### ISSUE TITLE
Nodes named "X subgebus X"

### ISSUE THREAD

**Issue by cleopatra17** [OpenTreeOfLife/reference-taxonomy#386]
I hope this question is in the right place.

271 nodes in the synthetic tree appear to have a name `X genus X`. eg [Equus subgenus Equus](https://tree.opentreeoflife.org/opentree/argus/ottol@94003/Equus-subgenus-Equus).

![Screenshot from 2021-06-21 22-02-23](https://user-images.githubusercontent.com/82857295/122866600-13662a00-d2dd-11eb-9b95-74f250906c60.png)

I wonder if these subgenuses lack a name, or if they result from a bug. In other words, is it safe to just remove those nodes and bring their children up one level, as direct children to the genus?

Thanks

**Comment by mtholder** [comment]
In some cases (particularly in animals) these nodes will be redundant. In the Intl. Code of Zoological Nomenclature, naming a genus implicitly names a subgenus with the same name. (e.g. the subgenus Equus in the genus Equus). This is typically omitted if there are no other name subgenera.
However, if there are other named subgenera in the genus, the subgenus with the same name as the genus will be a part of the taxonomy. In these cases, in the Open Tree Taxonomy, we insert the word "subgenus" into the name to make it unambiguous.
Sometimes the representatives of the other subgenera are extinct (or otherwise flagged as suspect during the building of the Open Tree Taxonomy), so the other subgenera may be present in the taxonomy, but absent in the synthetic tree.

In the case of Equus, synthetic tree 13.4 has other subgenera represented. See: https://tree.opentreeoflife.org/opentree/opentree13.4@ott541951/Equus Groups like Hemionus (https://tree.opentreeoflife.org/taxonomy/browse?id=615438 ) are also subgenera.

**Comment by cleopatra17** [comment]
Thanks @mtholder! So I understand that `Equus subgenus equus` is truly a subgenus, but it has been renamed to avoid confusing it with the genus `Equus`.

I have a follow up question then. Why can't that subgenus be named `Equus equus`, similar to [Gorilla gorilla](https://tree.opentreeoflife.org/opentree/argus/ottol@417965/Gorilla-gorilla)? Or are these two completely different cases?

Thank you very much for your help! I'm working on a visualisation of the OTOL data, and wanted to make sure I understanf those anomalies before I represent them in a potentially inaccurate way.

**Comment by mtholder** [comment]
The lower case name is a species level name or name for a taxon below the species level. So _Gorilla_ is a genus. _Gorilla gorilla_ is a species name, and _Gorilla gorilla gorilla_ is a subspecies within the species _Gorilla gorilla_. It's confusing, I know...

There is nothing to prevent a zoologist from naming a species of horse-like animal "_Equus equus_", but (as far as I know) no one has done this. However someone has named a group of species within the genus _Equus_ as a subgenus also called _Equus_.

Tautonyms are not allowed in the botanical code, see: https://en.wikipedia.org/wiki/Tautonym

**Comment by cleopatra17** [comment]
Thanks @mtholder. That clarifies everything.
