### ISSUE TITLE
taxa not in OTT but in IF and NCBI - probably fixed when these databases get updated?

### ISSUE THREAD

**Issue by rgazis** [OpenTreeOfLife/reference-taxonomy#42]
http://www.reelab.net/phylografter/otu/study/444

(1) http://www.indexfungorum.org/names/NamesRecord.asp?RecordID=189431
Phomopsis arctii = Diaporthe arctii

(2) Phomopsis pustulata = Diaporthe pustulata
http://www.ncbi.nlm.nih.gov/nuccore/AF408357
http://www.indexfungorum.org/names/NamesRecord.asp?RecordID=158211

(3) Valsa mali
http://www.indexfungorum.org/names/NamesRecord.asp?RecordID=184733
http://www.ncbi.nlm.nih.gov/nuccore/AF362559

http://www.reelab.net/phylografter/otu/study/747
(4) Genus Cyphellopsis
Not in IF
http://www.ncbi.nlm.nih.gov/nuccore/10799623

(5) Cystoderma chocoanum
http://www.indexfungorum.org/names/NamesRecord.asp?RecordID=360752
http://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi?id=56159

http://www.reelab.net/phylografter/otu/study/381

(6) Hypocrea lutea = Trichoderma deliquescens

http://www.indexfungorum.org/names/NamesRecord.asp?RecordID=269931

............. more soon....

**Comment by jar398** [comment]
OTT 2.8 says:
5342145	|	1057275	|	Cyphellopsis	|	genus	|	ncbi:139265,irmng:1117219	|	Cyphellopsis (genus in family Cyphellaceae)	|	sibling_lower,tattered	|	

This tells me that Cyphellopsis is not a taxon in our version Index Fungorum. Looking at the conflicts file it appears the genus (from NCBI) is seen as paraphyletic because the members of the NCBI taxon occur in different genera in Index Fungorum (which has species in the genus, but not the genus itself). To see the full list go to the NCBI taxonomy site. The fix is probably to add it, as a patch, to Index Fungorum, and figure out what is parent and children should be. Currently in IF C. anomala is placed in Merismodes (there's a synonym Merismodes anomala). The children of of Merismodes are
	 Merismodes granulosa(542284) species
	 Merismodes connivens(542283) species
	 Cyphellopsis changbaiensis(515096) species
	 Merismodes fasciculata(100240) species
	 Merismodes fulva(318507) species
	 Cyphellopsis anomala(250705) species
	 Cyphellopsis subglobispora(329524) species
	 Merismodes ochracea(334092) species
	 Merismodes mellea(318499) species
(if:317573. Merismodes volkensii)
(if:317571. Merismodes bresadolae)

It looks to me like someone decided Cyphellopsis was not clearly monophyletic and just lumped its species into Merismodes, and the database didn't update the species names.

Do you want me to do anything about this? If not I'll close this issue.

**Comment by jar398** [comment]
Not having received further guidance I'm closing this.
